// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFf3EdarQjhoVAs6nJ21_i0-ADhdsYZo',
    appId: '1:117058955229:web:38aa7c394041217143f834',
    messagingSenderId: '117058955229',
    projectId: 'food-delivery-9536c',
    authDomain: 'food-delivery-9536c.firebaseapp.com',
    storageBucket: 'food-delivery-9536c.firebasestorage.app',
    measurementId: 'G-35EFNQGNX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowSnDSvOxbFSuapfyZoRGo8w2p52ML2A',
    appId: '1:117058955229:android:15bb1af683b5197f43f834',
    messagingSenderId: '117058955229',
    projectId: 'food-delivery-9536c',
    storageBucket: 'food-delivery-9536c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4Xns6PMk2TSHMi0EiexRcRTKWiMruO4',
    appId: '1:117058955229:ios:d22e6584175a6fb143f834',
    messagingSenderId: '117058955229',
    projectId: 'food-delivery-9536c',
    storageBucket: 'food-delivery-9536c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4Xns6PMk2TSHMi0EiexRcRTKWiMruO4',
    appId: '1:117058955229:ios:d22e6584175a6fb143f834',
    messagingSenderId: '117058955229',
    projectId: 'food-delivery-9536c',
    storageBucket: 'food-delivery-9536c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoFf3EdarQjhoVAs6nJ21_i0-ADhdsYZo',
    appId: '1:117058955229:web:057952b56bd02d3743f834',
    messagingSenderId: '117058955229',
    projectId: 'food-delivery-9536c',
    authDomain: 'food-delivery-9536c.firebaseapp.com',
    storageBucket: 'food-delivery-9536c.firebasestorage.app',
    measurementId: 'G-6ZPQK7BZXM',
  );
}
